"""
Config module — fixed Nifty 100 universe and Trade Type parameter presets.
Per requirements doc: Universe is hardcoded (no Nifty 500 / custom list).
Trade Type is the single cascading switch that sets every downstream parameter.
"""

# ---------------------------------------------------------------------------
# Universe (fixed — Section 1 of requirements doc)
# ---------------------------------------------------------------------------
NIFTY_100_MAP = {
    "HDFCBANK": "HDFC Bank Ltd.",
    "ICICIBANK": "ICICI Bank Ltd.",
    "RELIANCE": "Reliance Industries Ltd.",
    "BHARTIARTL": "Bharti Airtel Ltd.",
    "LT": "Larsen & Toubro Ltd.",
    "SBIN": "State Bank of India",
    "INFY": "Infosys Ltd.",
    "AXISBANK": "Axis Bank Ltd.",
    "M&M": "Mahindra & Mahindra Ltd.",
    "BAJFINANCE": "Bajaj Finance Ltd.",
    "KOTAKBANK": "Kotak Mahindra Bank Ltd.",
    "ITC": "ITC Ltd.",
    "ETERNAL": "Eternal Ltd. (Zomato)",
    "TCS": "Tata Consultancy Services Ltd.",
    "TITAN": "Titan Company Ltd.",
    "SUNPHARMA": "Sun Pharmaceutical Industries Ltd.",
    "HINDUNILVR": "Hindustan Unilever Ltd.",
    "MARUTI": "Maruti Suzuki India Ltd.",
    "NTPC": "NTPC Ltd.",
    "SHRIRAMFIN": "Shriram Finance Ltd.",
    "TATASTEEL": "Tata Steel Ltd.",
    "HINDALCO": "Hindalco Industries Ltd.",
    "BEL": "Bharat Electronics Ltd.",
    "HCLTECH": "HCL Technologies Ltd.",
    "ULTRACEMCO": "UltraTech Cement Ltd.",
    "BAJAJ-AUTO": "Bajaj Auto Ltd.",
    "ADANIPORTS": "Adani Ports & SEZ Ltd.",
    "GRASIM": "Grasim Industries Ltd.",
    "JSWSTEEL": "JSW Steel Ltd.",
    "POWERGRID": "Power Grid Corp of India Ltd.",
    "ASIANPAINT": "Asian Paints Ltd.",
    "BAJAJFINSV": "Bajaj Finserv Ltd.",
    "INDIGO": "InterGlobe Aviation Ltd. (IndiGo)",
    "EICHERMOT": "Eicher Motors Ltd.",
    "DIVISLAB": "Divi's Laboratories Ltd.",
    "NESTLEIND": "Nestle India Ltd.",
    "TVSMOTOR": "TVS Motor Company Ltd.",
    "TECHM": "Tech Mahindra Ltd.",
    "TMCV": "Tata Motors Commercial Vehicles Ltd.",
    "TRENT": "Trent Ltd.",
    "COALINDIA": "Coal India Ltd.",
    "HAL": "Hindustan Aeronautics Ltd.",
    "ONGC": "Oil & Natural Gas Corp Ltd.",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Ltd.",
    "ADANIENT": "Adani Enterprises Ltd.",
    "ADANIPOWER": "Adani Power Ltd.",
    "CHOLAFIN": "Cholamandalam Investment & Fin Ltd.",
    "CIPLA": "Cipla Ltd.",
    "SBILIFE": "SBI Life Insurance Co. Ltd.",
    "JIOFIN": "Jio Financial Services Ltd.",
    "MOTHERSON": "Samvardhana Motherson Intl Ltd.",
    "TORNTPHARM": "Torrent Pharmaceuticals Ltd.",
    "MAXHEALTH": "Max Healthcare Institute Ltd.",
    "DRREDDY": "Dr. Reddy's Laboratories Ltd.",
    "CUMMINSIND": "Cummins India Ltd.",
    "TATACONSUM": "Tata Consumer Products Ltd.",
    "TMPV": "Tata Motors Passenger Vehicles Ltd.",
    "BRITANNIA": "Britannia Industries Ltd.",
    "DMART": "Avenue Supermarts Ltd. (DMart)",
    "INDHOTEL": "The Indian Hotels Co. Ltd.",
    "BPCL": "Bharat Petroleum Corp Ltd.",
    "TATAPOWER": "Tata Power Company Ltd.",
    "VBL": "Varun Beverages Ltd.",
    "CGPOWER": "CG Power & Industrial Solutions Ltd.",
    "HDFCLIFE": "HDFC Life Insurance Co. Ltd.",
    "PFC": "Power Finance Corporation Ltd.",
    "HDFCAMC": "HDFC Asset Management Co. Ltd.",
    "PIDILITIND": "Pidilite Industries Ltd.",
    "IOC": "Indian Oil Corporation Ltd.",
    "ADANIENSOL": "Adani Energy Solutions Ltd.",
    "WIPRO": "Wipro Ltd.",
    "BAJAJHLDNG": "Bajaj Holdings & Investment Ltd.",
    "SOLARINDS": "Solar Industries India Ltd.",
    "GAIL": "GAIL (India) Ltd.",
    "BANKBARODA": "Bank of Baroda",
    "VEDL": "Vedanta Ltd.",
    "UNITDSPR": "United Spirits Ltd.",
    "DLF": "DLF Ltd.",
    "CANBK": "Canara Bank",
    "ADANIGREEN": "Adani Green Energy Ltd.",
    "LTM": "LTIMindtree Ltd.",
    "BOSCHLTD": "Bosch Ltd.",
    "JINDALSTEL": "Jindal Steel & Power Ltd.",
    "PNB": "Punjab National Bank",
    "RECLTD": "REC Ltd.",
    "ABB": "ABB India Ltd.",
    "GODREJCP": "Godrej Consumer Products Ltd.",
    "UNIONBANK": "Union Bank of India",
    "LODHA": "Macrotech Developers Ltd. (Lodha)",
    "SIEMENS": "Siemens Ltd.",
    "SHREECEM": "Shree Cement Ltd.",
    "HYUNDAI": "Hyundai Motor India Ltd.",
    "MUTHOOTFIN": "Muthoot Finance Ltd.",
    "ENRIN": "Siemens Energy India Ltd.",  # corrected — was incorrectly "Niva Bupa Health Insurance Ltd."; Niva Bupa's real symbol is NIVABUPA
    "ZYDUSLIFE": "Zydus Lifesciences Ltd.",
    "HINDZINC": "Hindustan Zinc Ltd.",
    "AMBUJACEM": "Ambuja Cements Ltd.",
    "MAZDOCK": "Mazagon Dock Shipbuilders Ltd.",
    "TATACAP": "Tata Capital Ltd.",
    "IRFC": "Indian Railway Finance Corp Ltd.",
}

# Nifty 500 constituent list — sourced from official NSE data, verified
# accurate as of Aug 2026 (cross-checked against NIFTY_100_MAP for the
# ~100 overlapping symbols; this source also caught and fixed a real
# error in NIFTY_100_MAP's ENRIN mapping, see the fix above).
NIFTY_500_MAP = {
    "360ONE": "360 ONE WAM Ltd.",
    "3MINDIA": "3M India Ltd.",
    "ABB": "ABB India Ltd.",
    "ACC": "ACC Ltd.",
    "ACMESOLAR": "ACME Solar Holdings Ltd.",
    "AIAENG": "AIA Engineering Ltd.",
    "APLAPOLLO": "APL Apollo Tubes Ltd.",
    "AUBANK": "AU Small Finance Bank Ltd.",
    "AWL": "AWL Agri Business Ltd.",
    "AADHARHFC": "Aadhar Housing Finance Ltd.",
    "AARTIIND": "Aarti Industries Ltd.",
    "AAVAS": "Aavas Financiers Ltd.",
    "ABBOTINDIA": "Abbott India Ltd.",
    "ACE": "Action Construction Equipment Ltd.",
    "ACUTAAS": "Acutaas Chemicals Ltd.",
    "ADANIENSOL": "Adani Energy Solutions Ltd.",
    "ADANIENT": "Adani Enterprises Ltd.",
    "ADANIGREEN": "Adani Green Energy Ltd.",
    "ADANIPORTS": "Adani Ports and Special Economic Zone Ltd.",
    "ADANIPOWER": "Adani Power Ltd.",
    "ATGL": "Adani Total Gas Ltd.",
    "ABCAPITAL": "Aditya Birla Capital Ltd.",
    "ABFRL": "Aditya Birla Fashion and Retail Ltd.",
    "ABLBL": "Aditya Birla Lifestyle Brands Ltd.",
    "ABREL": "Aditya Birla Real Estate Ltd.",
    "ABSLAMC": "Aditya Birla Sun Life AMC Ltd.",
    "CPPLUS": "Aditya Infotech Ltd.",
    "AEGISLOG": "Aegis Logistics Ltd.",
    "AEGISVOPAK": "Aegis Vopak Terminals Ltd.",
    "AFCONS": "Afcons Infrastructure Ltd.",
    "AFFLE": "Affle 3i Ltd.",
    "AJANTPHARM": "Ajanta Pharmaceuticals Ltd.",
    "ALKEM": "Alkem Laboratories Ltd.",
    "ABDL": "Allied Blenders and Distillers Ltd.",
    "ARE&M": "Amara Raja Energy & Mobility Ltd.",
    "AMBER": "Amber Enterprises India Ltd.",
    "AMBUJACEM": "Ambuja Cements Ltd.",
    "ANANDRATHI": "Anand Rathi Wealth Ltd.",
    "ANANTRAJ": "Anant Raj Ltd.",
    "ANGELONE": "Angel One Ltd.",
    "ANTHEM": "Anthem Biosciences Ltd.",
    "ANURAS": "Anupam Rasayan India Ltd.",
    "APARINDS": "Apar Industries Ltd.",
    "APOLLOHOSP": "Apollo Hospitals Enterprise Ltd.",
    "APOLLOTYRE": "Apollo Tyres Ltd.",
    "APTUS": "Aptus Value Housing Finance India Ltd.",
    "ASAHIINDIA": "Asahi India Glass Ltd.",
    "ASHOKLEY": "Ashok Leyland Ltd.",
    "ASIANPAINT": "Asian Paints Ltd.",
    "ASTERDM": "Aster DM Quality Care Ltd.",
    "ASTRAL": "Astral Ltd.",
    "ATHERENERG": "Ather Energy Ltd.",
    "ATUL": "Atul Ltd.",
    "AUROPHARMA": "Aurobindo Pharma Ltd.",
    "AIIL": "Authum Investment & Infrastructure Ltd.",
    "DMART": "Avenue Supermarts Ltd.",
    "AXISBANK": "Axis Bank Ltd.",
    "BEML": "BEML Ltd.",
    "BLS": "BLS International Services Ltd.",
    "BSE": "BSE Ltd.",
    "BAJAJ-AUTO": "Bajaj Auto Ltd.",
    "BAJFINANCE": "Bajaj Finance Ltd.",
    "BAJAJFINSV": "Bajaj Finserv Ltd.",
    "BAJAJHLDNG": "Bajaj Holdings & Investment Ltd.",
    "BAJAJHFL": "Bajaj Housing Finance Ltd.",
    "BALKRISIND": "Balkrishna Industries Ltd.",
    "BALRAMCHIN": "Balrampur Chini Mills Ltd.",
    "BANDHANBNK": "Bandhan Bank Ltd.",
    "BANKBARODA": "Bank of Baroda",
    "BANKINDIA": "Bank of India",
    "MAHABANK": "Bank of Maharashtra",
    "BATAINDIA": "Bata India Ltd.",
    "BAYERCROP": "Bayer Cropscience Ltd.",
    "BELRISE": "Belrise Industries Ltd.",
    "BERGEPAINT": "Berger Paints India Ltd.",
    "BDL": "Bharat Dynamics Ltd.",
    "BEL": "Bharat Electronics Ltd.",
    "BHARATFORG": "Bharat Forge Ltd.",
    "BHEL": "Bharat Heavy Electricals Ltd.",
    "BPCL": "Bharat Petroleum Corporation Ltd.",
    "BHARTIARTL": "Bharti Airtel Ltd.",
    "BHARTIHEXA": "Bharti Hexacom Ltd.",
    "BIKAJI": "Bikaji Foods International Ltd.",
    "GROWW": "Billionbrains Garage Ventures Ltd.",
    "BIOCON": "Biocon Ltd.",
    "BSOFT": "Birlasoft Ltd.",
    "BLUEDART": "Blue Dart Express Ltd.",
    "BLUEJET": "Blue Jet Healthcare Ltd.",
    "BLUESTARCO": "Blue Star Ltd.",
    "BBTC": "Bombay Burmah Trading Corporation Ltd.",
    "BOSCHLTD": "Bosch Ltd.",
    "FIRSTCRY": "Brainbees Solutions Ltd.",
    "BRIGADE": "Brigade Enterprises Ltd.",
    "BRITANNIA": "Britannia Industries Ltd.",
    "MAPMYINDIA": "C.E. Info Systems Ltd.",
    "CCL": "CCL Products (I) Ltd.",
    "CESC": "CESC Ltd.",
    "CGPOWER": "CG Power and Industrial Solutions Ltd.",
    "CIEINDIA": "CIE Automotive India Ltd.",
    "CRISIL": "CRISIL Ltd.",
    "CANFINHOME": "Can Fin Homes Ltd.",
    "CANBK": "Canara Bank",
    "CANHLIFE": "Canara HSBC Life Insurance Company Ltd.",
    "CAPLIPOINT": "Caplin Point Laboratories Ltd.",
    "CGCL": "Capri Global Capital Ltd.",
    "CARBORUNIV": "Carborundum Universal Ltd.",
    "CARTRADE": "Cartrade Tech Ltd.",
    "CASTROLIND": "Castrol India Ltd.",
    "CEATLTD": "Ceat Ltd.",
    "CEMPRO": "Cemindia Projects Ltd.",
    "CENTRALBK": "Central Bank of India",
    "CDSL": "Central Depository Services (India) Ltd.",
    "CHALET": "Chalet Hotels Ltd.",
    "CHAMBLFERT": "Chambal Fertilizers & Chemicals Ltd.",
    "CHENNPETRO": "Chennai Petroleum Corporation Ltd.",
    "CHOICEIN": "Choice International Ltd.",
    "CHOLAHLDNG": "Cholamandalam Financial Holdings Ltd.",
    "CHOLAFIN": "Cholamandalam Investment and Finance Company Ltd.",
    "CIPLA": "Cipla Ltd.",
    "CUB": "City Union Bank Ltd.",
    "CLEAN": "Clean Science and Technology Ltd.",
    "COALINDIA": "Coal India Ltd.",
    "COCHINSHIP": "Cochin Shipyard Ltd.",
    "COFORGE": "Coforge Ltd.",
    "COHANCE": "Cohance Lifesciences Ltd.",
    "COLPAL": "Colgate Palmolive (India) Ltd.",
    "CAMS": "Computer Age Management Services Ltd.",
    "CONCORDBIO": "Concord Biotech Ltd.",
    "CONCOR": "Container Corporation of India Ltd.",
    "COROMANDEL": "Coromandel International Ltd.",
    "CRAFTSMAN": "Craftsman Automation Ltd.",
    "CREDITACC": "CreditAccess Grameen Ltd.",
    "CROMPTON": "Crompton Greaves Consumer Electricals Ltd.",
    "CUMMINSIND": "Cummins India Ltd.",
    "CYIENT": "Cyient Ltd.",
    "DCMSHRIRAM": "DCM Shriram Ltd.",
    "DLF": "DLF Ltd.",
    "DOMS": "DOMS Industries Ltd.",
    "DABUR": "Dabur India Ltd.",
    "DALBHARAT": "Dalmia Bharat Ltd.",
    "DATAPATTNS": "Data Patterns (India) Ltd.",
    "DEEPAKFERT": "Deepak Fertilisers & Petrochemicals Corp. Ltd.",
    "DEEPAKNTR": "Deepak Nitrite Ltd.",
    "DELHIVERY": "Delhivery Ltd.",
    "DEVYANI": "Devyani International Ltd.",
    "DIVISLAB": "Divi's Laboratories Ltd.",
    "DIXON": "Dixon Technologies (India) Ltd.",
    "LALPATHLAB": "Dr. Lal Path Labs Ltd.",
    "DRREDDY": "Dr. Reddy's Laboratories Ltd.",
    "EIDPARRY": "E.I.D. Parry (India) Ltd.",
    "EIHOTEL": "EIH Ltd.",
    "EICHERMOT": "Eicher Motors Ltd.",
    "ELECON": "Elecon Engineering Co. Ltd.",
    "ELGIEQUIP": "Elgi Equipments Ltd.",
    "EMAMILTD": "Emami Ltd.",
    "EMCURE": "Emcure Pharmaceuticals Ltd.",
    "EMMVEE": "Emmvee Photovoltaic Power Ltd.",
    "ENDURANCE": "Endurance Technologies Ltd.",
    "ENGINERSIN": "Engineers India Ltd.",
    "ERIS": "Eris Lifesciences Ltd.",
    "ESCORTS": "Escorts Kubota Ltd.",
    "ETERNAL": "Eternal Ltd.",
    "EXIDEIND": "Exide Industries Ltd.",
    "NYKAA": "FSN E-Commerce Ventures Ltd.",
    "FEDERALBNK": "Federal Bank Ltd.",
    "FACT": "Fertilisers and Chemicals Travancore Ltd.",
    "FINCABLES": "Finolex Cables Ltd.",
    "FSL": "Firstsource Solutions Ltd.",
    "FIVESTAR": "Five-Star Business Finance Ltd.",
    "FORCEMOT": "Force Motors Ltd.",
    "FORTIS": "Fortis Healthcare Ltd.",
    "GAIL": "GAIL (India) Ltd.",
    "GVT&D": "GE Vernova T&D India Ltd.",
    "GMRAIRPORT": "GMR Airports Ltd.",
    "GABRIEL": "Gabriel India Ltd.",
    "GALLANTT": "Gallantt Ispat Ltd.",
    "GRSE": "Garden Reach Shipbuilders & Engineers Ltd.",
    "GICRE": "General Insurance Corporation of India",
    "GILLETTE": "Gillette India Ltd.",
    "GLAND": "Gland Pharma Ltd.",
    "GLAXO": "Glaxosmithkline Pharmaceuticals Ltd.",
    "GLENMARK": "Glenmark Pharmaceuticals Ltd.",
    "MEDANTA": "Global Health Ltd.",
    "GODIGIT": "Go Digit General Insurance Ltd.",
    "GPIL": "Godawari Power & Ispat Ltd.",
    "GODFRYPHLP": "Godfrey Phillips India Ltd.",
    "GODREJCP": "Godrej Consumer Products Ltd.",
    "GODREJIND": "Godrej Industries Ltd.",
    "GODREJPROP": "Godrej Properties Ltd.",
    "GRANULES": "Granules India Ltd.",
    "GRAPHITE": "Graphite India Ltd.",
    "GRASIM": "Grasim Industries Ltd.",
    "GRAVITA": "Gravita India Ltd.",
    "GESHIP": "Great Eastern Shipping Co. Ltd.",
    "FLUOROCHEM": "Gujarat Fluorochemicals Ltd.",
    "GMDCLTD": "Gujarat Mineral Development Corporation Ltd.",
    "HEG": "H.E.G. Ltd.",
    "HBLENGINE": "HBL Engineering Ltd.",
    "HCLTECH": "HCL Technologies Ltd.",
    "HDBFS": "HDB Financial Services Ltd.",
    "HDFCAMC": "HDFC Asset Management Company Ltd.",
    "HDFCBANK": "HDFC Bank Ltd.",
    "HDFCLIFE": "HDFC Life Insurance Company Ltd.",
    "HFCL": "HFCL Ltd.",
    "HAVELLS": "Havells India Ltd.",
    "HEROMOTOCO": "Hero MotoCorp Ltd.",
    "HEXT": "Hexaware Technologies Ltd.",
    "HSCL": "Himadri Speciality Chemical Ltd.",
    "HINDALCO": "Hindalco Industries Ltd.",
    "HAL": "Hindustan Aeronautics Ltd.",
    "HINDCOPPER": "Hindustan Copper Ltd.",
    "HINDPETRO": "Hindustan Petroleum Corporation Ltd.",
    "HINDUNILVR": "Hindustan Unilever Ltd.",
    "HINDZINC": "Hindustan Zinc Ltd.",
    "POWERINDIA": "Hitachi Energy India Ltd.",
    "HOMEFIRST": "Home First Finance Company India Ltd.",
    "HONASA": "Honasa Consumer Ltd.",
    "HONAUT": "Honeywell Automation India Ltd.",
    "HUDCO": "Housing & Urban Development Corporation Ltd.",
    "HYUNDAI": "Hyundai Motor India Ltd.",
    "ICICIBANK": "ICICI Bank Ltd.",
    "ICICIGI": "ICICI Lombard General Insurance Company Ltd.",
    "ICICIAMC": "ICICI Prudential Asset Management Company Ltd.",
    "ICICIPRULI": "ICICI Prudential Life Insurance Company Ltd.",
    "IDBI": "IDBI Bank Ltd.",
    "IDFCFIRSTB": "IDFC First Bank Ltd.",
    "IFCI": "IFCI Ltd.",
    "IIFL": "IIFL Finance Ltd.",
    "IRB": "IRB Infrastructure Developers Ltd.",
    "IRCON": "IRCON International Ltd.",
    "ITCHOTELS": "ITC Hotels Ltd.",
    "ITC": "ITC Ltd.",
    "ITI": "ITI Ltd.",
    "INDGN": "Indegene Ltd.",
    "INDIACEM": "India Cements Ltd.",
    "INDIAMART": "Indiamart Intermesh Ltd.",
    "INDIANB": "Indian Bank",
    "IEX": "Indian Energy Exchange Ltd.",
    "INDHOTEL": "Indian Hotels Co. Ltd.",
    "IOC": "Indian Oil Corporation Ltd.",
    "IOB": "Indian Overseas Bank",
    "IRCTC": "Indian Railway Catering And Tourism Corporation Ltd.",
    "IRFC": "Indian Railway Finance Corporation Ltd.",
    "IREDA": "Indian Renewable Energy Development Agency Ltd.",
    "IGL": "Indraprastha Gas Ltd.",
    "INDUSTOWER": "Indus Towers Ltd.",
    "INDUSINDBK": "IndusInd Bank Ltd.",
    "NAUKRI": "Info Edge (India) Ltd.",
    "INFY": "Infosys Ltd.",
    "INOXWIND": "Inox Wind Ltd.",
    "INTELLECT": "Intellect Design Arena Ltd.",
    "INDIGO": "InterGlobe Aviation Ltd.",
    "IGIL": "International Gemological Institute Ltd.",
    "IKS": "Inventurus Knowledge Solutions Ltd.",
    "IPCALAB": "Ipca Laboratories Ltd.",
    "JKCEMENT": "J.K. Cement Ltd.",
    "JBMA": "JBM Auto Ltd.",
    "JKTYRE": "JK Tyre & Industries Ltd.",
    "JMFINANCIL": "JM Financial Ltd.",
    "JSWCEMENT": "JSW Cement Ltd.",
    "JSWDULUX": "JSW Dulux Ltd.",
    "JSWENERGY": "JSW Energy Ltd.",
    "JSWINFRA": "JSW Infrastructure Ltd.",
    "JSWSTEEL": "JSW Steel Ltd.",
    "JAINREC": "Jain Resource Recycling Ltd.",
    "JPPOWER": "Jaiprakash Power Ventures Ltd.",
    "J&KBANK": "Jammu & Kashmir Bank Ltd.",
    "JINDALSAW": "Jindal Saw Ltd.",
    "JSL": "Jindal Stainless Ltd.",
    "JINDALSTEL": "Jindal Steel Ltd.",
    "JIOFIN": "Jio Financial Services Ltd.",
    "JUBLFOOD": "Jubilant Foodworks Ltd.",
    "JUBLINGREA": "Jubilant Ingrevia Ltd.",
    "JUBLPHARMA": "Jubilant Pharmova Ltd.",
    "JWL": "Jupiter Wagons Ltd.",
    "JYOTICNC": "Jyoti CNC Automation Ltd.",
    "KPRMILL": "K.P.R. Mill Ltd.",
    "KEI": "KEI Industries Ltd.",
    "KPITTECH": "KPIT Technologies Ltd.",
    "KAJARIACER": "Kajaria Ceramics Ltd.",
    "KPIL": "Kalpataru Projects International Ltd.",
    "KALYANKJIL": "Kalyan Jewellers India Ltd.",
    "KARURVYSYA": "Karur Vysya Bank Ltd.",
    "KAYNES": "Kaynes Technology India Ltd.",
    "KEC": "Kec International Ltd.",
    "KFINTECH": "Kfin Technologies Ltd.",
    "KIRLOSENG": "Kirloskar Oil Eng Ltd.",
    "KOTAKBANK": "Kotak Mahindra Bank Ltd.",
    "KIMS": "Krishna Institute of Medical Sciences Ltd.",
    "LTF": "L&T Finance Ltd.",
    "LTTS": "L&T Technology Services Ltd.",
    "LGEINDIA": "LG Electronics India Ltd.",
    "LICHSGFIN": "LIC Housing Finance Ltd.",
    "LTFOODS": "LT Foods Ltd.",
    "LTM": "LTM Ltd.",
    "LT": "Larsen & Toubro Ltd.",
    "LATENTVIEW": "Latent View Analytics Ltd.",
    "LAURUSLABS": "Laurus Labs Ltd.",
    "THELEELA": "Leela Palaces Hotels & Resorts Ltd.",
    "LEMONTREE": "Lemon Tree Hotels Ltd.",
    "LENSKART": "Lenskart Solutions Ltd.",
    "LICI": "Life Insurance Corporation of India",
    "LINDEINDIA": "Linde India Ltd.",
    "LLOYDSME": "Lloyds Metals And Energy Ltd.",
    "LODHA": "Lodha Developers Ltd.",
    "LUPIN": "Lupin Ltd.",
    "MMTC": "MMTC Ltd.",
    "MRF": "MRF Ltd.",
    "MGL": "Mahanagar Gas Ltd.",
    "M&MFIN": "Mahindra & Mahindra Financial Services Ltd.",
    "M&M": "Mahindra & Mahindra Ltd.",
    "MANAPPURAM": "Manappuram Finance Ltd.",
    "MRPL": "Mangalore Refinery & Petrochemicals Ltd.",
    "MANKIND": "Mankind Pharma Ltd.",
    "MARICO": "Marico Ltd.",
    "MARUTI": "Maruti Suzuki India Ltd.",
    "MFSL": "Max Financial Services Ltd.",
    "MAXHEALTH": "Max Healthcare Institute Ltd.",
    "MAZDOCK": "Mazagoan Dock Shipbuilders Ltd.",
    "MEESHO": "Meesho Ltd.",
    "MINDACORP": "Minda Corporation Ltd.",
    "MSUMI": "Motherson Sumi Wiring India Ltd.",
    "MOTILALOFS": "Motilal Oswal Financial Services Ltd.",
    "MPHASIS": "MphasiS Ltd.",
    "MCX": "Multi Commodity Exchange of India Ltd.",
    "MUTHOOTFIN": "Muthoot Finance Ltd.",
    "NATCOPHARM": "NATCO Pharma Ltd.",
    "NBCC": "NBCC (India) Ltd.",
    "NCC": "NCC Ltd.",
    "NHPC": "NHPC Ltd.",
    "NLCINDIA": "NLC India Ltd.",
    "NMDC": "NMDC Ltd.",
    "NSLNISP": "NMDC Steel Ltd.",
    "NTPCGREEN": "NTPC Green Energy Ltd.",
    "NTPC": "NTPC Ltd.",
    "NH": "Narayana Hrudayalaya Ltd.",
    "NATIONALUM": "National Aluminium Co. Ltd.",
    "NAVA": "Nava Ltd.",
    "NAVINFLUOR": "Navin Fluorine International Ltd.",
    "NESTLEIND": "Nestle India Ltd.",
    "NETWEB": "Netweb Technologies India Ltd.",
    "NEULANDLAB": "Neuland Laboratories Ltd.",
    "NEWGEN": "Newgen Software Technologies Ltd.",
    "NAM-INDIA": "Nippon Life India Asset Management Ltd.",
    "NIVABUPA": "Niva Bupa Health Insurance Company Ltd.",
    "NUVAMA": "Nuvama Wealth Management Ltd.",
    "NUVOCO": "Nuvoco Vistas Corporation Ltd.",
    "OBEROIRLTY": "Oberoi Realty Ltd.",
    "ONGC": "Oil & Natural Gas Corporation Ltd.",
    "OIL": "Oil India Ltd.",
    "OLAELEC": "Ola Electric Mobility Ltd.",
    "OLECTRA": "Olectra Greentech Ltd.",
    "PAYTM": "One 97 Communications Ltd.",
    "ONESOURCE": "Onesource Specialty Pharma Ltd.",
    "OFSS": "Oracle Financial Services Software Ltd.",
    "POLICYBZR": "PB Fintech Ltd.",
    "PCBL": "PCBL Chemical Ltd.",
    "PGEL": "PG Electroplast Ltd.",
    "PIIND": "PI Industries Ltd.",
    "PNBHOUSING": "PNB Housing Finance Ltd.",
    "PTCIL": "PTC Industries Ltd.",
    "PVRINOX": "PVR INOX Ltd.",
    "PAGEIND": "Page Industries Ltd.",
    "PARADEEP": "Paradeep Phosphates Ltd.",
    "PATANJALI": "Patanjali Foods Ltd.",
    "PERSISTENT": "Persistent Systems Ltd.",
    "PETRONET": "Petronet LNG Ltd.",
    "PFIZER": "Pfizer Ltd.",
    "PHOENIXLTD": "Phoenix Mills Ltd.",
    "PWL": "Physicswallah Ltd.",
    "PIDILITIND": "Pidilite Industries Ltd.",
    "PINELABS": "Pine Labs Ltd.",
    "PIRAMALFIN": "Piramal Finance Ltd.",
    "PPLPHARMA": "Piramal Pharma Ltd.",
    "POLYMED": "Poly Medicure Ltd.",
    "POLYCAB": "Polycab India Ltd.",
    "POONAWALLA": "Poonawalla Fincorp Ltd.",
    "PFC": "Power Finance Corporation Ltd.",
    "POWERGRID": "Power Grid Corporation of India Ltd.",
    "PREMIERENE": "Premier Energies Ltd.",
    "PRESTIGE": "Prestige Estates Projects Ltd.",
    "PFOCUS": "Prime Focus Ltd.",
    "PNB": "Punjab National Bank",
    "RRKABEL": "R R Kabel Ltd.",
    "RBLBANK": "RBL Bank Ltd.",
    "RECLTD": "REC Ltd.",
    "RHIM": "RHI MAGNESITA INDIA LTD.",
    "RITES": "RITES Ltd.",
    "RADICO": "Radico Khaitan Ltd",
    "RVNL": "Rail Vikas Nigam Ltd.",
    "RAILTEL": "Railtel Corporation Of India Ltd.",
    "RAINBOW": "Rainbow Childrens Medicare Ltd.",
    "RKFORGE": "Ramkrishna Forgings Ltd.",
    "REDINGTON": "Redington Ltd.",
    "RELIANCE": "Reliance Industries Ltd.",
    "RPOWER": "Reliance Power Ltd.",
    "SBFC": "SBFC Finance Ltd.",
    "SBICARD": "SBI Cards and Payment Services Ltd.",
    "SBILIFE": "SBI Life Insurance Company Ltd.",
    "SJVN": "SJVN Ltd.",
    "SRF": "SRF Ltd.",
    "SAGILITY": "Sagility Ltd.",
    "SAILIFE": "Sai Life Sciences Ltd.",
    "SAMMAANCAP": "Sammaan Capital Ltd.",
    "MOTHERSON": "Samvardhana Motherson International Ltd.",
    "SAPPHIRE": "Sapphire Foods India Ltd.",
    "SARDAEN": "Sarda Energy and Minerals Ltd.",
    "SAREGAMA": "Saregama India Ltd",
    "SCHAEFFLER": "Schaeffler India Ltd.",
    "SCHNEIDER": "Schneider Electric Infrastructure Ltd.",
    "SCI": "Shipping Corporation of India Ltd.",
    "SHREECEM": "Shree Cement Ltd.",
    "SHRIRAMFIN": "Shriram Finance Ltd.",
    "SHYAMMETL": "Shyam Metalics and Energy Ltd.",
    "ENRIN": "Siemens Energy India Ltd.",
    "SIEMENS": "Siemens Ltd.",
    "SIGNATURE": "Signatureglobal (India) Ltd.",
    "SOBHA": "Sobha Ltd.",
    "SOLARINDS": "Solar Industries India Ltd.",
    "SONACOMS": "Sona BLW Precision Forgings Ltd.",
    "SONATSOFTW": "Sonata Software Ltd.",
    "STARHEALTH": "Star Health and Allied Insurance Company Ltd.",
    "SBIN": "State Bank of India",
    "SAIL": "Steel Authority of India Ltd.",
    "SUMICHEM": "Sumitomo Chemical India Ltd.",
    "SUNPHARMA": "Sun Pharmaceutical Industries Ltd.",
    "SUNTV": "Sun TV Network Ltd.",
    "SUNDARMFIN": "Sundaram Finance Ltd.",
    "SUPREMEIND": "Supreme Industries Ltd.",
    "SPLPETRO": "Supreme Petrochem Ltd.",
    "SUZLON": "Suzlon Energy Ltd.",
    "SWANCORP": "Swan Corp Ltd.",
    "SWIGGY": "Swiggy Ltd.",
    "SYNGENE": "Syngene International Ltd.",
    "SYRMA": "Syrma SGS Technology Ltd.",
    "TBOTEK": "TBO Tek Ltd.",
    "TVSMOTOR": "TVS Motor Company Ltd.",
    "TATACAP": "Tata Capital Ltd.",
    "TATACHEM": "Tata Chemicals Ltd.",
    "TATACOMM": "Tata Communications Ltd.",
    "TCS": "Tata Consultancy Services Ltd.",
    "TATACONSUM": "Tata Consumer Products Ltd.",
    "TATAELXSI": "Tata Elxsi Ltd.",
    "TATAINVEST": "Tata Investment Corporation Ltd.",
    "TMCV": "Tata Motors Ltd.",
    "TMPV": "Tata Motors Passenger Vehicles Ltd.",
    "TATAPOWER": "Tata Power Co. Ltd.",
    "TATASTEEL": "Tata Steel Ltd.",
    "TATATECH": "Tata Technologies Ltd.",
    "TTML": "Tata Teleservices (Maharashtra) Ltd.",
    "TECHM": "Tech Mahindra Ltd.",
    "TECHNOE": "Techno Electric & Engineering Company Ltd.",
    "TEGA": "Tega Industries Ltd.",
    "TEJASNET": "Tejas Networks Ltd.",
    "TENNIND": "Tenneco Clean Air India Ltd.",
    "NIACL": "The New India Assurance Company Ltd.",
    "RAMCOCEM": "The Ramco Cements Ltd.",
    "THERMAX": "Thermax Ltd.",
    "TIMKEN": "Timken India Ltd.",
    "TITAGARH": "Titagarh Rail Systems Ltd.",
    "TITAN": "Titan Company Ltd.",
    "TORNTPHARM": "Torrent Pharmaceuticals Ltd.",
    "TORNTPOWER": "Torrent Power Ltd.",
    "TARIL": "Transformers And Rectifiers (India) Ltd.",
    "TRAVELFOOD": "Travel Food Services Ltd.",
    "TRENT": "Trent Ltd.",
    "TRIDENT": "Trident Ltd.",
    "TRITURBINE": "Triveni Turbine Ltd.",
    "TIINDIA": "Tube Investments of India Ltd.",
    "UCOBANK": "UCO Bank",
    "UNOMINDA": "UNO Minda Ltd.",
    "UPL": "UPL Ltd.",
    "UTIAMC": "UTI Asset Management Company Ltd.",
    "ULTRACEMCO": "UltraTech Cement Ltd.",
    "UNIONBANK": "Union Bank of India",
    "UBL": "United Breweries Ltd.",
    "UNITDSPR": "United Spirits Ltd.",
    "URBANCO": "Urban Company Ltd.",
    "USHAMART": "Usha Martin Ltd.",
    "VTL": "Vardhman Textiles Ltd.",
    "VBL": "Varun Beverages Ltd.",
    "VEDL": "Vedanta Ltd.",
    "VIJAYA": "Vijaya Diagnostic Centre Ltd.",
    "VMM": "Vishal Mega Mart Ltd.",
    "IDEA": "Vodafone Idea Ltd.",
    "VOLTAS": "Voltas Ltd.",
    "WAAREEENER": "Waaree Energies Ltd.",
    "WELCORP": "Welspun Corp Ltd.",
    "WELSPUNLIV": "Welspun Living Ltd.",
    "WHIRLPOOL": "Whirlpool of India Ltd.",
    "WIPRO": "Wipro Ltd.",
    "WOCKPHARMA": "Wockhardt Ltd.",
    "YESBANK": "Yes Bank Ltd.",
    "ZFCVINDIA": "ZF Commercial Vehicle Control Systems India Ltd.",
    "ZEEL": "Zee Entertainment Enterprises Ltd.",
    "ZENTEC": "Zen Technologies Ltd.",
    "ZENSARTECH": "Zensar Technolgies Ltd.",
    "ZYDUSLIFE": "Zydus Lifesciences Ltd.",
    "ZYDUSWELL": "Zydus Wellness Ltd.",
    "ECLERX": "eClerx Services Ltd.",
}

NSE_SUFFIX = ".NS"


def yf_symbol(nse_symbol: str) -> str:
    """Convert an NSE ticker (e.g. 'INFY') to its yfinance symbol ('INFY.NS')."""
    return f"{nse_symbol}{NSE_SUFFIX}"


# ---------------------------------------------------------------------------
# Trade Type parameter presets (Section 4 of requirements doc)
# Trade Type is the ONLY user-facing switch — every value below is derived
# from it, never individually exposed as a raw filter.
# ---------------------------------------------------------------------------
TRADE_TYPE_PARAMS = {
    "short_term": {
        "label": "Short-term",
        "sr_lookback_months": 4,          # 3-6 months -> default mid-point
        "sr_lookback_days": 90,           # approx trading days for 4 months
        "fractal_width": 5,               # candles either side
        "min_touch_separation_days": 7,
        "primary_trend_ma": 20,
        "pattern_prior_trend_lookback": 7,  # candles
    },
    "long_term": {
        "label": "Long-term",
        "sr_lookback_months": 15,         # 12-18 months -> default mid-point
        "sr_lookback_days": 320,          # approx trading days for 15 months
        "fractal_width": 10,
        "min_touch_separation_days": 15,
        "primary_trend_ma": 50,
        "pattern_prior_trend_lookback": 15,
    },
}

DEFAULT_TRADE_TYPE = "short_term"

# ---------------------------------------------------------------------------
# Parameters constant regardless of Trade Type
# ---------------------------------------------------------------------------
SR_ZONE_TOLERANCE_PCT = 1.0            # zone buffer, % of price (was 0.75%, widened)
SR_MAX_DISTANCE_PCT_DEFAULT = 4.0      # max allowed % gap between candle-SL and nearest S/R zone, user-editable
SL_BUFFER_PCT = 0.3                    # buffer beyond the candle low/high used for the actual stop-loss
MAX_CUSTOM_TICKERS = 50                # cap on user-entered custom ticker list, not persisted across sessions
VOLUME_MA_PERIOD_DEFAULT = 10          # days, user-configurable in UI
MIN_RR_DEFAULT = 2.0                   # user-configurable in UI
MARUBOZU_SHADOW_TOLERANCE_PCT = 7.0    # fixed system parameter, NOT a UI filter
TREND_SLOPE_LOOKBACK_DAYS = 12         # for MA slope up/down check
SIDEWAYS_FLIP_WINDOW = 10              # candles checked for MA-crossing flips
SIGNAL_SCAN_LOOKBACK_DAYS = 30         # live-computed signal scan window (Section 5)

# Indicator periods — same for both Trade Types in v1 (Section 3.3 / Section 9 v2 item)
RSI_PERIOD = 14
MACD_FAST, MACD_SLOW, MACD_SIGNAL = 12, 26, 9
SUPERTREND_PERIOD, SUPERTREND_MULTIPLIER = 10, 3
AROON_PERIOD = 14